### ISSUE TITLE
How to call 'new' method of GDScript class

### ISSUE THREAD

**Issue by MANKEYYENAME** [godot-d/godot-d#79]
I haven't idea, because `typeof(someScript._new)` is `GDScript`, not `Variant`. Also `__traits(getMember, scr, "new")` doesn't work.

**Comment by sheepandshepherd** [comment]
Oh, I didn't notice that name conflict before. It's trying to use the static `_new()` internally called by `memnew`. This will be fixed in the next compatibility-breaking update, which removes the static `_new()`, since it's just a leftover from how the C++ bindings implemented Godot class construction (`memnew!GDScript` in Godot-D).

For now, here are two workarounds that call GDScript's `new` function properly:
```d
Ref!GDScript someScript = ResourceLoader.load(gs!"res://some_gdscript.gd").as!GDScript;

// Option 1: call it through script API
Variant instance = someScript.call(gs!"new");
// Option 2: force it to use the correct `_new`, a template function
Variant instance = someScript._new!()();

print(instance);
instance.as!GodotObject.call(gs!"some_function", 1, 2, 3);
```

**Comment by MANKEYYENAME** [comment]
Thank you!
